# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

# - uses: actions/checkout@v3
# - uses: actions/setup-python@v4

# The easiest way to stay current is to enable Dependabot for GitHub Actions.

# Then add a file to your repo to enable dependabot (/.github/dependabot.yml) for actions:

# version: 2
# updates:
#   - package-ecosystem: "github-actions"

    #directory: "/" 
    #schedule:
      #interval: "weekly"

